(deftheme wfv-color
  "Created 2017-04-03.")

(custom-theme-set-variables
 'wfv-color
 '(custom-safe-themes (quote ("1651d8d8793a68425206636eb6eddaadcea0a5893e86533456092f37ce4d8cba" "cb4043174063dd4ecef0979403613cbdce8f1a6035404f422f2e480d0524e050" "734f21e68230313dcc77120a853c7fc962c627b41a4656566d09f3ffb0fffa2b" default)))
 '(which-function-mode t)
 '(electric-pair-mode t)
 '(package-selected-packages (quote (erlang toml-mode company-ghci company-ghc company-erlang company cargo restclient rust-mode magit))))

(custom-theme-set-faces
 'wfv-color
 '(error ((t (:foreground "firebrick1" :weight bold))))
 '(fringe ((t (:background "gray35"))))
 '(highlight ((t (:background "gray21"))))
 '(isearch ((t (:background "coral1" :foreground "gray26"))))
 '(link ((t (:foreground "SteelBlue1" :underline t))))
 '(minibuffer-prompt ((t (:foreground "SteelBlue1"))))
 '(mode-line ((t (:background "gray55" :foreground "black" :box (:line-width -1 :style released-button)))))
 '(org-date ((t (:foreground "turquoise" :underline t))))
 '(org-document-info ((t (:foreground "white smoke" :slant italic))))
 '(org-document-title ((t (:foreground "white" :weight bold))))
 '(org-footnote ((t (:inherit link))))
 '(org-table ((t (:foreground "DodgerBlue1"))))
 '(region ((t (:background "slate grey"))))
 '(shadow ((t (:foreground "grey16"))))
 '(show-paren-match ((t (:background "gold" :foreground "black"))))
 '(show-paren-mismatch ((t (:background "deep pink" :foreground "gray18"))))
 '(which-func ((t (:foreground "maroon3"))))
 '(org-done ((t (:foreground "#8ae234"))))
 '(org-level-4 ((t (:inherit outline-7))))
 '(org-level-7 ((t (:inherit outline-4))))
 '(org-todo ((t (:foreground "Maroon2"))))
 '(font-lock-type-face ((nil (:inherit default :foreground "#8ae234" :weight normal))))
 '(font-lock-builtin-face ((nil (:inherit font-lock-type-face :weight normal))))
 '(font-lock-comment-face ((nil (:inherit default :foreground "#888a85" :slant italic))))
 '(font-lock-string-face ((nil (:inherit default :foreground "#34e4ea" :slant italic))))
 '(font-lock-warning-face ((((class color) (min-colors 88) (background dark)) (:inherit default :foreground "#db2763" :weight bold))))
 '(font-lock-constant-face ((t (:inherit font-lock-variable-name-face :foreground "white" :slant normal))))
 '(font-lock-doc-face ((t (:inherit default :foreground "gray65" :slant italic))))
 '(font-lock-function-name-face ((t (:inherit default :foreground "Maroon2" :slant normal))))
 '(font-lock-keyword-face ((t (:inherit default :foreground "white"))))
 '(font-lock-preprocessor-face ((t (:inherit default :foreground "#fdca40" :weight normal))))
 '(font-lock-variable-name-face ((t (:inherit default :foreground "DeepSkyBlue1"))))
 '(default ((t (:inherit nil :stipple nil :background "#464646" :foreground "gray70" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal)))))

(provide-theme 'wfv-color)
